### ISSUE TITLE
在一个图片数组中怎么选中第几张

### ISSUE THREAD

**Issue by yimouren** [Alfred-Skyblue/v3-img-preview#3]
比如我现在有一个图片数组，我点击第二张进行预览，我应该预览的是第二张，而不是从第一张开始，要怎么传参控制从第几张开始预览呢

**Comment by yimouren** [comment]
在源码里看到有index的入参了，可能没有更新到文档，如果有时间的话最好更新一下哈，谢谢

**Comment by Alfred-Skyblue** [comment]
https://alfred-skyblue.github.io/v3-img-preview/guide/#api

**Comment by yimouren** [comment]
你好，你的邮件我已经收到，将会尽快处理，谢谢。
